version: "3"
services:
  bhui:
    container_name: my-ui-container
    image: bookhunt_ui
    build: ./book-hunt-ui
    hostname: my.bhui.intranet
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - books-network
    depends_on:
      - bhservice

  bhservice:
    container_name: servicecontainer
    image: bookhunt_service
    build: ./BookHuntService
    hostname: my.bhservice.intranet
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - books-network

networks:
  books-network:
