export const PUT_ERRORS ="ERRORS";
export const RECEIVE_FILTERED_BOOKS = "RECEIVE_FILTERED_BOOKS";
export const CLEAR_FILTERED_BOOKS = "CLEAR_FILTERED_BOOKS";
export const CLEAR_ERRORS ="CLEAR_ERRORS";